blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
  - name: Repo Discussions
    url: https://github.com/abhi-murthy/MDLearning/discussions
    about: Please report security vulnerabilities here.
