# This is a basic workflow to help you get started with Actions

name: Learning Github Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  demo-job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
    # Steps represent a sequence of tasks that will be executed as part of the job

  demo-job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: demo-job1
    steps:
      - run: echo "Hello, world 2"
      - run: sleep 10s

  demo-job3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: demo-job2
    steps:
      - run: |
          echo "Hello World 3",
          echo "End of the world".
